// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nyoskxqyduprsqznyzmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55b3NreHF5ZHVwcnNxem55em1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjA3NDAsImV4cCI6MjA3MTE5Njc0MH0.k1vlASDGtZYxX3G6MV0Vq15jCYqBmjuOWTbPpSChV4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});